name: Workflow for Codecov example-typescript
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import # One-time step
          curl -Os https://cli.codecov.io/latest/linux/codecov
          curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM
          curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM.sig

          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM

          shasum -a 256 -c codecov.SHA256SUM
          sudo chmod +x codecov
          sudo mv codecov /usr/local/bin/
          codecov --auto-load-params-from GithubActions -u http://143.198.145.7 --verbose upload-process --disable-search -f coverage/cobertura-coverage.xml -F test;
